"""
Django settings for ICE project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# BASE_DIR is directory where manage.py lives.
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@onqjcn651eg^&g1(kabn7+kp)0(!_gal3k+=8cjawh(jd*%-e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['GhostStories.pythonanywhere.com']
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'monk.python@gmail.com'
EMAIL_HOST_PASSWORD = 'iamhappy'
EMAIL_PORT = 587


# Application definition

INSTALLED_APPS = [
# placed directly above admin , so that it use custom templates instead of django admin.
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    #CUSTOM APPS
    'Blog',
    'WriteBlog',

    #third party apps
    'crispy_forms',
    'registration',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ICE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ICE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'GhostStories$P_ICE',
        'USER': 'GhostStories',
        'PASSWORD': '9780@maN',
        'HOST': 'GhostStories.mysql.pythonanywhere-services.com',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# django will look for these directiories along with looking in each app for static files.
# this is where weare going to store our static files.
STATICFILES_DIRS = [
# our static files will be stored at /Static/OurStatic/next
    os.path.join(BASE_DIR, "Blog", "Static"),
    os.path.join(BASE_DIR, "WriteBlog", "Static"),
        
]

# collectstatic command will move all static folders in this directory.
# server will look for this directory.
# root(admin) static files will be saved at /Static/RootStatic
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'Static')


#MEDIA
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Static', "Media")

#django registration settings
REGISTARTION_OPEN = True # if true users can register.
ACCOUNT_ACTIVATION_DAYS = 4 # number of days within which user can activate account.
REGISTARTION_AUTO_LOGIN = True # if true users will be automatically logged in.
LOGIN_REDIRECT_URL = '/home' # The page users will arrive at, after successful log in.
LOGIN_URL = '/accounts/login/' # The page users are directed to, if they are not logged in.

SITE_ID = 1

# crispy form settings
CRISPY_TEMPLATE_PACK = 'bootstrap3'